### ISSUE TITLE
HR not adding it's own OD increase to PP calculations

### ISSUE THREAD

**Issue by BabySnakes101** [KatK1/taikopp.com#4]
### **OD 7**
![image](https://github.com/KatK1/taikopp.com/assets/86463950/ae13e169-485f-451b-987a-357449c816f0)
### **OD 9.8 (HR)**
![image](https://github.com/KatK1/taikopp.com/assets/86463950/05674f89-3356-4db5-abf0-fa3990b174d5)
### **OD 9.8 (Non HR)**
![image](https://github.com/KatK1/taikopp.com/assets/86463950/62d1cbf6-950e-4eb1-a84b-20feea007c78)

**Comment by KatK1** [comment]
fixed: [commit here](https://github.com/KatK1/taikopp.com/commit/3a21087478337a0951b1665fc14f8cf73e89eb56)
